version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout:
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Check Code Formatting
          command: ./gradlew ktlintCheck
      - run:
          name: Run Tests
          command: ./gradlew test
      - run:
          name: Assemble
          command: ./gradlew assemble --continue

workflows:
  version: 2
  workflow:
    jobs:
      - build